### ISSUE TITLE
Crashes when playing music

### ISSUE THREAD

**Issue by aleszczynskig** [mpbzh/homebridge-plex#14] opened 2018-02-15 09:23 UTC
Hi, this is working for me perfectly well when I back video however when i play music the plugin crashes Homebridge with the following error.

 18:25:14] [Plex Audio Sensor] There is one active session:
Feb 14 18:25:14 raspberrypi homebridge[25473]: /opt/node/lib/node_modules/homebridge-plex/index.js:83
Feb 14 18:25:14 raspberrypi homebridge[25473]:         data.Video.forEach(function (e)

Thank you for developing this however is it possible to enable this to work for music as well as video. And as a feature request is it possible to add that as a filter so that it is possible in HomeKit to have two triggers, one for music and one for video. In my situation I would want to trigger different scenes based upon the content that is playing.

Many Thanks

**Comment by mpbzh** [comment] 2018-02-15 11:00
Good catch! Thanks for reporting, I'll fix that.

**Comment by aleszczynskig** [comment] 2018-02-15 13:38
That’s great. Glad I could help and I look forward to the update!

**Comment by ghost** [comment] 2018-02-19 00:22
Oh nice. I'm glad @aleszczynskig found the cause of this crash. I was just looking at my logs again today and noticed the same errors (which of course all line up with my music plays). Thanks!

**Comment by kendickson** [comment] 2018-03-16 09:31
Changing line 83 from "data.Video.forEach" to "data.Metadata.forEach" fixes it on my Plex setup (server 1.12.1.4871) – playing either video or music now trigger "Occupancy Detected".

**Comment by mpbzh** [comment] 2018-04-10 14:45
Thanks for posting your solution, @kendickson. 
Can anyone else confirm this works? My Plex API does not return a `Metadata` field.

**Comment by mpbzh** [comment] 2019-11-08 20:34
This should be fixed. Please update `homebridge-plex` and reopen the issue if the error persists.

**Closed as completed by mpbzh** 2019-11-08 20:34 UTC
Labels: bug, in progress
